version: '3'
services:
  front:
    build:
      context: ./front
    ports:
      - "4200:4200"
    volumes:
      - ./front:/app
    command: npm start
    networks:
      - my_network
    environment:
      - CHOKIDAR_USEPOLLING=true

  back:
    build:
      context: ./back
    ports:
      - "3000:3000"  # Mapea el puerto 3000 del host al puerto 3000 del contenedor del back-end
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
    