pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Clona el repositorio
                git url: 'https://github.com/Sebas10casti/poli-integracion-continua.git', branch: 'main'
            }
        }

        stage('Build and Run Frontend') {
            steps {
                dir('front') {
                    // Construir la imagen del frontend usando el Dockerfile específico
                    sh 'docker build -t front-app -f Dockerfile .'
                    // Ejecutar el contenedor del frontend
                    sh 'docker run -d -p 4200:4200 --network my_network front-app'
                }
            }
        }
    }

    post {
        always {
            // Detener y eliminar los contenedores después de la ejecución
            sh 'docker stop $(docker ps -a -q)'
            sh 'docker rm $(docker ps -a -q)'
        }
    }
}
